---
title: "BollingerBands"
author: "cyber-atlas"
date: "April 23, 2019"
output: html_document
---
 
```{r}
# install.packages("quantmod")
library('quantmod')
library('ggplot2')
# install.packages("magrittr")
library('magrittr')
install.packages("tidyquant")
library('tidyquant')
```

Getting the data

```{r}
#Define start and End dates
start <- as.Date("2018-04-25")
end <- as.Date("2019-04-25")
getSymbols(c("AAPL", "AMD", "SPY", "MU"), src="yahoo", from = start, to = end)

```

Bollinger bands are fundamentally based on the simple moving average, so lets get that

```{r}
#Charts the prices of the SPY 500
candleChart(SPY, up.col="green", dn.col="red", theme="white")
#Adds the simple moving average
plot(addSMA(n = 20))

#Extract taht data
#use function lines t
```

```{r}

candleChart(SPY, up.col="green", dn.col="red", theme="white")
addMACD()
```


```{r}

candleChart(SPY, up.col="green", dn.col="red", theme="white")
#Adds Bollinger Bands
addBBands()



```

```{r}
chartSeries(AMD, type='candlesticks')

```



Went through a lot of the quantmod documentation to find this info paired with the financial analysis I have been trying to teach myself. 

https://cran.r-project.org/web/packages/quantmod/index.html 